# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "'Star Wars' }, { name: "'Lord of the Rings' }])
#   Character.create(name: "'Luke', movie: movies.first)

Garnish.create(name: "Allspice)
Garnish.create(name: "Andes Crème de Menthe Thin)
Garnish.create(name: "Angostura Bitters)
Garnish.create(name: "Apple)
Garnish.create(name: "Apple Fan)
Garnish.create(name: "Apple Slices)
Garnish.create(name: "Bacon)
Garnish.create(name: "Banana)
Garnish.create(name: "Basil)
Garnish.create(name: "Blackberries)
Garnish.create(name: "Blackberry)
Garnish.create(name: "Blood Orange)
Garnish.create(name: "Blueberries)
Garnish.create(name: "Brandied Cherries)
Garnish.create(name: "Brandied Cherry)
Garnish.create(name: "Butterscotch Syrup)
Garnish.create(name: "Candied Ginger)
Garnish.create(name: "Cardamom)
Garnish.create(name: "Cayenne Pepper)
Garnish.create(name: "CBD Oil)
Garnish.create(name: "Celery)
Garnish.create(name: "Chamoe or Honeydew)
Garnish.create(name: "Cherry)
Garnish.create(name: "Chile Piquin Rim)
Garnish.create(name: "Chile Powder)
Garnish.create(name: "Chocolate)
Garnish.create(name: "Chocolate Shavings)
Garnish.create(name: "Chocolate Syrup Rim)
Garnish.create(name: "Chopped Lemongrass )
Garnish.create(name: "Cilantro)
Garnish.create(name: "Cinnamon)
Garnish.create(name: "Citrus)
Garnish.create(name: "Clove)
Garnish.create(name: "Clove-Studded Lemon)
Garnish.create(name: "Cocoa)
Garnish.create(name: "Cocoa Powder)
Garnish.create(name: "Coffee)
Garnish.create(name: "Corn Chip)
Garnish.create(name: "Cracked Pepper)
Garnish.create(name: "Cranberries)
Garnish.create(name: "Crushed Candy Cane)
Garnish.create(name: "Crushed Oreo Cookies)
Garnish.create(name: "Cucumber)
Garnish.create(name: "Dehydrated Beetroot Sugar)
Garnish.create(name: "Dehydrated Lemon)
Garnish.create(name: "Dried Hibiscus Flowers)
Garnish.create(name: "Edible Flower)
Garnish.create(name: "Edible Orchid)
Garnish.create(name: "Espresso)
Garnish.create(name: "Flamed Orange)
Garnish.create(name: "Flamed Rosemary)
Garnish.create(name: "Flaming Lime)
Garnish.create(name: "Fortune Cookie)
Garnish.create(name: "Ginger)
Garnish.create(name: "Gold)
Garnish.create(name: "Grapefruit)
Garnish.create(name: "Grapefruit Wheel Quarter)
Garnish.create(name: "Grated Cinnamon)
Garnish.create(name: "Grated Nutmeg)
Garnish.create(name: "Green Apple)
Garnish.create(name: "Green Olive)
Garnish.create(name: "Ground Black Pepper)
Garnish.create(name: "Ground Cayenne)
Garnish.create(name: "Half Orange Slice)
Garnish.create(name: "Jalapeño)
Garnish.create(name: "Jalapeño Pepper)
Garnish.create(name: "Jasmine Flower)
Garnish.create(name: "Juniper Berries)
Garnish.create(name: "La Boíte Borneo N. 26 Spice Mix)
Garnish.create(name: "Lemon)
Garnish.create(name: "Lemon Oil)
Garnish.create(name: "Lemon or Orange)
Garnish.create(name: "Lemon-Basil)
Garnish.create(name: "Lime)
Garnish.create(name: "Makrut Lime)
Garnish.create(name: "Makrut Lime Leaf)
Garnish.create(name: "Maraschino Cherries)
Garnish.create(name: "Maraschino Cherry)
Garnish.create(name: "Medjool Date)
Garnish.create(name: "Melted Chocolate Chips)
Garnish.create(name: "Mini Marshmallows)
Garnish.create(name: "Mint)
Garnish.create(name: "Nutmeg)
Garnish.create(name: "Olive or Lemon)
Garnish.create(name: "Orange)
Garnish.create(name: "Orange Blossom)
Garnish.create(name: "Orange Blossom Bubbles)
Garnish.create(name: "Orange or Lemon)
Garnish.create(name: "Orange Wheel Half)
Garnish.create(name: ")
Garnish.create(name: "Oregano)
Garnish.create(name: "Organic Thyme)
Garnish.create(name: ")
Garnish.create(name: "Pandan Leaf)
Garnish.create(name: "Passion Fruit)
Garnish.create(name: ")
Garnish.create(name: "Passion Fruit Half)
Garnish.create(name: "Peach)
Garnish.create(name: "Peeps Marshmallows)
Garnish.create(name: "Peychaud’s Bitters )
Garnish.create(name: "Pine)
Garnish.create(name: "Pineapple)
Garnish.create(name: "Pineapple or Orange)
Garnish.create(name: "Pomegranate Seeds)
Garnish.create(name: "Pumpkin)
Garnish.create(name: "Queso Fresco)
Garnish.create(name: "Red Hot Chile Pepper)
Garnish.create(name: "Red Pepper Flakes)
Garnish.create(name: "Red Rose)
Garnish.create(name: "Rock Candy)
Garnish.create(name: "Rose Salt)
Garnish.create(name: "Rosemary)
Garnish.create(name: "Rosemary or Thyme)
Garnish.create(name: "Sage)
Garnish.create(name: "Salt Rim)
Garnish.create(name: "Salted Glass)
Garnish.create(name: "Sea Salt)
Garnish.create(name: "Shredded Toasted Coconut)
Garnish.create(name: "Silverskin Onion)
Garnish.create(name: "Skewered Apples)
Garnish.create(name: "Skewered Raspberries)
Garnish.create(name: "Sliced Ginger)
Garnish.create(name: "Smoked Paprika)
Garnish.create(name: "Speared Cherries)
Garnish.create(name: "Spearmint)
Garnish.create(name: "Star Anise)
Garnish.create(name: "Stirrer)
Garnish.create(name: "Strawberries)
Garnish.create(name: "Strawberry)
Garnish.create(name: "Sugar Rim)
Garnish.create(name: "Sugarcane)
Garnish.create(name: "Sugared Cranberries)
Garnish.create(name: "Sweet Pepper)
Garnish.create(name: "Thai Chile Pepper)
Garnish.create(name: "Thyme)
Garnish.create(name: "Toblerone Chocolate)
Garnish.create(name: "Trimmed Coconut)
Garnish.create(name: "Umbrella)
Garnish.create(name: "Unpeeled Apple)
Garnish.create(name: "Vanilla Sugar)
Garnish.create(name: "Watermelon)
Garnish.create(name: "Whipped Cream)
Garnish.create(name: "White Grapes)
Garnish.create(name: "Whole Candy Cane)
Garnish.create(name: "Whole Cloves)
Mixer.create(name: "7 Up)
Mixer.create(name: "Activated Charcoal)
Mixer.create(name: "Agave Nectar)
Mixer.create(name: "Agave Syrup)
Mixer.create(name: "Almond Milk)
Mixer.create(name: "Angostura Bitters)
Mixer.create(name: "Angostura Orange Bitters)
Mixer.create(name: "Apple Bitters)
Mixer.create(name: "Apple Cider)
Mixer.create(name: "Apple Cider Syrup)
Mixer.create(name: "Apple Cider Vinegar)
Mixer.create(name: "Apple Juice)
Mixer.create(name: "Apricot Syrup)
Mixer.create(name: "Aromatic Bitters)
Mixer.create(name: "Aromatic Tonic Water)
Mixer.create(name: "Assorted Seasonal Fruit)
Mixer.create(name: "Avocado)
Mixer.create(name: "B.G. Reynolds Don's Spices #2)
Mixer.create(name: "Baked Macintosh Apple)
Mixer.create(name: "Basil)
Mixer.create(name: "Beet Juice)
Mixer.create(name: "Bittermens Tiki Bitters)
Mixer.create(name: "Bitters)
Mixer.create(name: "Black Pepper)
Mixer.create(name: "Black Sesame Orgeat)
Mixer.create(name: "Black Tea)
Mixer.create(name: "Black Walnut Bitters)
Mixer.create(name: "Blackberries)
Mixer.create(name: "Blackberry Jam)
Mixer.create(name: "Blackberry Sage Tea Syrup)
Mixer.create(name: "Black-Cocoa-And-Range Syrup)
Mixer.create(name: "Blood Orange Juice)
Mixer.create(name: "Blueberries)
Mixer.create(name: "Boiling Water)
Mixer.create(name: "Boiron Passion Fruit Purée)
Mixer.create(name: "Brazilian Espresso)
Mixer.create(name: "Brewed Black Tea)
Mixer.create(name: "Brewed Coffee)
Mixer.create(name: "Brewed Dark-Roast Coffee)
Mixer.create(name: "Brown Sugar)
Mixer.create(name: "Carbonated Water)
Mixer.create(name: "Cardamom Rock Candy Syrup)
Mixer.create(name: "Cardamom Syrup)
Mixer.create(name: "Carrot Cordial)
Mixer.create(name: "Carrot-Ginger Juice)
Mixer.create(name: "CBD-Ginger Syrup)
Mixer.create(name: "CBD-Infused Zero-Sugar Sparkling Citrus Soda)
Mixer.create(name: "Celery Bitters)
Mixer.create(name: "Celery Salt)
Mixer.create(name: "Chai Tea)
Mixer.create(name: "Chamoe Juice (or Honeydew Juice))
Mixer.create(name: "Chamomile Cordial)
Mixer.create(name: "Chamomile Tea)
Mixer.create(name: "Cherry Kombucha)
Mixer.create(name: "Chili Powder)
Mixer.create(name: "Chilled Water)
Mixer.create(name: "Chinese Five-Spice Powder)
Mixer.create(name: "Chocolate Bitters)
Mixer.create(name: "Chocolate Ice Cream)
Mixer.create(name: "Chocolate Mole Bitters)
Mixer.create(name: "Chocolate Syrup)
Mixer.create(name: "Chocomole Mixture)
Mixer.create(name: "Chopped pear)
Mixer.create(name: "Chopped Pineapple)
Mixer.create(name: "Chopped Semisweet Chocolate)
Mixer.create(name: "Chopped Tart Apples)
Mixer.create(name: "Chopped Unsweetened Chocolate)
Mixer.create(name: "Cider)
Mixer.create(name: "Cinnamon)
Mixer.create(name: "Cinnamon Simple Syrup)
Mixer.create(name: "Cinnamon Vanilla Syrup)
Mixer.create(name: "Citrus Syrup)
Mixer.create(name: "Clamato Juice)
Mixer.create(name: "Club Soda)
Mixer.create(name: "Coarse Sea Salt)
Mixer.create(name: "Cocktailpunk Alpino Bitters)
Mixer.create(name: "Coconut Cream)
Mixer.create(name: "Coconut Milk)
Mixer.create(name: "Coconut Syrup)
Mixer.create(name: "Coconut Water)
Mixer.create(name: "Coconut Water Ice Ball)
Mixer.create(name: "Coffee Ice Cream)
Mixer.create(name: "Coffee-Infused Salt)
Mixer.create(name: "Cola)
Mixer.create(name: "Cola )
Mixer.create(name: "Cold-Brew Coffee)
Mixer.create(name: "Condensed Milk )
Mixer.create(name: "Cored and Chunked Granny Smith Apples)
Mixer.create(name: "Cored and Diced Apple)
Mixer.create(name: "Cracked Black Pepper)
Mixer.create(name: "Cran-Apple Juice)
Mixer.create(name: "Cranberry Juice)
Mixer.create(name: "Cream)
Mixer.create(name: "Cream of Coconut)
Mixer.create(name: "Cream Soda)
Mixer.create(name: "Crème de Coconut)
Mixer.create(name: "Crushed Ice)
Mixer.create(name: "Cucumber)
Mixer.create(name: "Cucumber Juice)
Mixer.create(name: "Cucumber Syrup)
Mixer.create(name: "Demerara Simple Syrup)
Mixer.create(name: "Demerara Sugar)
Mixer.create(name: "Demerara Syrup)
Mixer.create(name: "Donn’s Mix (2 parts Fresh Yellow Grapefruit, 1 part Cinnamon Syrup))
Mixer.create(name: "Don's Gardenia mix)
Mixer.create(name: "Earl Grey Tea)
Mixer.create(name: "Egg White)
Mixer.create(name: "Egg Yolk)
Mixer.create(name: "Eggnog)
Mixer.create(name: "Espresso)
Mixer.create(name: "Evaporated Milk)
Mixer.create(name: "Fassionola Syrup)
Mixer.create(name: "Fee Brothers Old Fashion Bitters)
Mixer.create(name: "Fennel Bitters)
Mixer.create(name: "Finely-Chopped Onion)
Mixer.create(name: "Frankincense Essential Oil )
Mixer.create(name: "Fresh Cream)
Mixer.create(name: "Fruit Juice)
Mixer.create(name: "Ghia)
Mixer.create(name: "Ginger)
Mixer.create(name: "Ginger Ale)
Mixer.create(name: "Ginger Beer)
Mixer.create(name: "Ginger Honey Syrup)
Mixer.create(name: "Ginger Juice)
Mixer.create(name: "Ginger Syrup)
Mixer.create(name: "Goji Ginger Syrup)
Mixer.create(name: "Gourmet Cotton Candy)
Mixer.create(name: "Grapefruit Juice)
Mixer.create(name: "Grapefruit Soda)
Mixer.create(name: "Green Olive Cocktail Brine)
Mixer.create(name: "Green Tea Syrup)
Mixer.create(name: "Grenadine)
Mixer.create(name: "Ground Cayenne Pepper)
Mixer.create(name: "Ground Cinnamon)
Mixer.create(name: "Ground Nutmeg)
Mixer.create(name: "Ground Pepper)
Mixer.create(name: "Guava Juice)
Mixer.create(name: "Guava Nectar)
Mixer.create(name: "Half and Half)
Mixer.create(name: "Heated Milk)
Mixer.create(name: "Heavy Cream)
Mixer.create(name: "Hibiscus Lavender Oak Bitters)
Mixer.create(name: "Himalayan Pink salt and Tajín seasoning Mix (1:1))
Mixer.create(name: "Honey)
Mixer.create(name: "Honey Mix)
Mixer.create(name: "Honey Sage Syrup)
Mixer.create(name: "Honey Syrup)
Mixer.create(name: "Hot Buttered Rum Batter)
Mixer.create(name: "Hot Hibiscus Tea)
Mixer.create(name: "Hot Sauce)
Mixer.create(name: "Hot Spiced Apple Cider)
Mixer.create(name: "Hot Water)
Mixer.create(name: "Hot Coffee)
Mixer.create(name: "Ice)
Mixer.create(name: "Instant Vanilla Pudding)
Mixer.create(name: "Jalapeño Pepper)
Mixer.create(name: "Japanese Kuromitsu (Can Substitute Honey or Molasses) )
Mixer.create(name: "Juiced Lemon)
Mixer.create(name: "Juiced Lime)
Mixer.create(name: "Juiced Lime Half)
Mixer.create(name: "Juiced Orange)
Mixer.create(name: "Large Eggs)
Mixer.create(name: "Large Strawberries)
Mixer.create(name: "Latitude 29 Formula Orgeat)
Mixer.create(name: "Lemon)
Mixer.create(name: "Lemon Bitters)
Mixer.create(name: "Lemon Juice)
Mixer.create(name: "Lemon Sorbet)
Mixer.create(name: "Lemon Squash)
Mixer.create(name: "Lemonade)
Mixer.create(name: "Lemon-Lime Soda)
Mixer.create(name: "Lemons)
Mixer.create(name: "Light Cream)
Mixer.create(name: "Lime Juice)
Mixer.create(name: "Limeade)
Mixer.create(name: "Maldon Salt)
Mixer.create(name: "Mango Juice)
Mixer.create(name: "Mango Purée)
Mixer.create(name: "Mango Vinegar)
Mixer.create(name: "Mango-Pandan Syrup)
Mixer.create(name: "Maple Syrup)
Mixer.create(name: "Maraschino Cherry)
Mixer.create(name: "Milk)
Mixer.create(name: "Mineral Saline)
Mixer.create(name: "Mineral Water)
Mixer.create(name: "Mint)
Mixer.create(name: "Mint Extract)
Mixer.create(name: "Mint Simple Syrup)
Mixer.create(name: "Mole Bitters)
Mixer.create(name: "MSG)
Mixer.create(name: "Old Fashioned Bitters)
Mixer.create(name: "Orange)
Mixer.create(name: "Orange Bitters)
Mixer.create(name: "Orange Blossom Water)
Mixer.create(name: "Orange Flower Water)
Mixer.create(name: "Orange Juice)
Mixer.create(name: "Orange Peel Oil)
Mixer.create(name: "Orange Sherbet)
Mixer.create(name: "Organic Heavy Cream)
Mixer.create(name: "Orgeat)
Mixer.create(name: "Orgeat Syrup)
Mixer.create(name: "Palm Sugar Syrup)
Mixer.create(name: "Pandan Cordial)
Mixer.create(name: "Pandan Syrup)
Mixer.create(name: "Passion Fruit Puree)
Mixer.create(name: "Passion Fruit Syrup)
Mixer.create(name: "Peach Purée)
Mixer.create(name: "Pebble Ice)
Mixer.create(name: "Peeled and Sliced Ginger)
Mixer.create(name: "Peychaud’s Bitters)
Mixer.create(name: "Pho Broth)
Mixer.create(name: "Piloncillo (Mexican-Style Unrefined Brown Sugar))
Mixer.create(name: "Pimento Bitters)
Mixer.create(name: "Pine Syrup)
Mixer.create(name: "Pineapple Juice)
Mixer.create(name: "Pineapple Purée)
Mixer.create(name: "Pineapple Shrub)
Mixer.create(name: "Pink Grapefruit Juice)
Mixer.create(name: "Pink Grapefruit Soda)
Mixer.create(name: "Pomegranate Juice)
Mixer.create(name: "Powdered Sugar)
Mixer.create(name: "Prepared Horseradish)
Mixer.create(name: "Pumpkin Puree)
Mixer.create(name: "Pumpkin Soda)
Mixer.create(name: "Pumpkin Syrup)
Mixer.create(name: "PX Sherry-Infused Butter)
Mixer.create(name: "Q Tonic Water)
Mixer.create(name: "Quartered Lemons)
Mixer.create(name: "Quartered Limes)
Mixer.create(name: "Quartered Orange)
Mixer.create(name: "Raisins)
Mixer.create(name: "Raspberries )
Mixer.create(name: "Raspberry Syrup)
Mixer.create(name: "Raw Egg)
Mixer.create(name: "Raw Sushi-Grade Tuna)
Mixer.create(name: "Red Hot Chili Pepper)
Mixer.create(name: "Red Wine Vinegar)
Mixer.create(name: "Root Beer)
Mixer.create(name: "Rose Flower Water)
Mixer.create(name: "Ruby Red Grapefruit Juice)
Mixer.create(name: "Saline Solution)
Mixer.create(name: "Salt)
Mixer.create(name: "Sea Salt)
Mixer.create(name: "Seltzer)
Mixer.create(name: "Separated Eggs)
Mixer.create(name: "Simple Syrup)
Mixer.create(name: "Smoked Cherry Bitters)
Mixer.create(name: "Smoked Honey)
Mixer.create(name: "Smoked-Rosemary Simple Syrup)
Mixer.create(name: "Soda Water)
Mixer.create(name: "Sour Mix)
Mixer.create(name: "Sparkling Cider)
Mixer.create(name: "Sparkling Water)
Mixer.create(name: "Spiced Honey Syrup)
Mixer.create(name: "Spiced Orange Ginger Ale)
Mixer.create(name: "Spicy Ginger Ale)
Mixer.create(name: "Split Vanilla Bean)
Mixer.create(name: "Sprite)
Mixer.create(name: "Squeezed Lime Half)
Mixer.create(name: "Star Anise)
Mixer.create(name: "Steamed Milk)
Mixer.create(name: "Strawberries)
Mixer.create(name: "Strawberry)
Mixer.create(name: "Strawberry Shrub)
Mixer.create(name: "Strawberry Syrup)
Mixer.create(name: "Strawberry-Rose Syrup)
Mixer.create(name: "Strong Espresso)
Mixer.create(name: "Strong-Brewed Black Tea)
Mixer.create(name: "Sugar)
Mixer.create(name: "Sugar Cane Juice)
Mixer.create(name: "Sugar Syrup)
Mixer.create(name: "Sweetened Coconut Milk Syrup)
Mixer.create(name: "Sweetened Condensed Milk)
Mixer.create(name: "Tabasco)
Mixer.create(name: "Tabasco Sauce)
Mixer.create(name: "Tamarind Paste)
Mixer.create(name: "Tapatio Hot Sauce)
Mixer.create(name: "Tartaric Acid Solution)
Mixer.create(name: "Tea Syrup)
Mixer.create(name: "Thai Coconut Milk)
Mixer.create(name: "Thistle)
Mixer.create(name: "Tom & Jerry Batter)
Mixer.create(name: "Tomato Juice)
Mixer.create(name: "Tonic Water)
Mixer.create(name: "Unsalted Butter)
Mixer.create(name: "Unsweetened Cocoa Powder)
Mixer.create(name: "Unsweetened Coconut Water)
Mixer.create(name: "Unsweetened Iced Tea)
Mixer.create(name: "Unsweetened Passion Fruit Purée)
Mixer.create(name: "Vanilla Extract)
Mixer.create(name: "Vanilla Ice Cream)
Mixer.create(name: "Vanilla Salt)
Mixer.create(name: "Vanilla Syrup)
Mixer.create(name: "Water)
Mixer.create(name: "Watermelon)
Mixer.create(name: "Watermelon (cubed))
Mixer.create(name: "Wedged Lime)
Mixer.create(name: "Wedged Orange)
Mixer.create(name: "White Chocolate Chips)
Mixer.create(name: "White Verjus)
Mixer.create(name: "Whole Cloves)
Mixer.create(name: "Whole Egg)
Mixer.create(name: "Whole Milk)
Mixer.create(name: "Worcestershire Sauce)
Mixer.create(name: "Yerba Mate Tea)
Mixer.create(name: "Yuzu Bitters)
Mixer.create(name: "Tonic Water)
Mixer.create(name: "Citrus Oleo-Saccharum)
Mixer.create(name: "Aurora Hemp-Infused Beverage)
